# Generated by Django 4.1.1 on 2022-09-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment', verbose_name='Equipo del jugador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Posicion del jugador'),
        ),
    ]
